apiVersion: 1.0
metadata:
  codeName: "com.custom.xnxx_plugin"
  prettyName: "xnxx External Plugin"
  version: v0.1.0
  developer: ""
  contactEmail: ""
  description: "External plugin template targeting xnxx.com"
  updateUrl: ""
  issuesUrl: ""

providerData:
  iconUrl: "https://xnxx.com/favicon.ico"
  serviceUrl: "https://xnxx.com"
  handleUrls:
    - "https://xnxx.com/home"
    - "https://xnxx.com/search"
    - "https://xnxx.com/video"
    - "https://xnxx.com/author"

initialPageCounts:
  initialHomePage: 0
  initialSearchResultsPage: 0
  initialCommentsPage: 0
  initialVideoSuggestionsPage: 0
  initialAuthorVideosPage: 0
